/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Etudiant;
import dao.EtudiantDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class PanelEtudiant extends javax.swing.JPanel {

    /**
     * Creates new form PanelEtudiant
     */
    public PanelEtudiant() {
        initComponents();
        listeEtudiant();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_classe = new javax.swing.JTextField();
        txt_telephone = new javax.swing.JFormattedTextField();
        btn_enregistrer = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_etudiant = new javax.swing.JTable();

        jLabel1.setText("Nom");

        jLabel2.setText("Prénom");

        jLabel3.setText("Classe");

        jLabel4.setText("Téléphone");

        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        tb_etudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ide", "Nom", "Prénom", "Classe", "Téléphone"
            }
        ));
        tb_etudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_etudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_etudiant);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txt_prenom)
                            .addComponent(txt_classe)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_enregistrer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_supprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_modifier))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_telephone)
                                .addGap(141, 141, 141)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enregistrer)
                    .addComponent(btn_supprimer)
                    .addComponent(btn_modifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        // TODO add your handling code here:
        String nom = txt_nom.getText();
        String prenom = txt_prenom.getText();
        String classe = txt_classe.getText();
        String telephone = txt_telephone.getText();
        Etudiant et = new Etudiant(nom, prenom, classe, telephone);
        EtudiantDao edao = new EtudiantDao();
        edao.ajouter(et);
        vider();
        listeEtudiant();
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // TODO add your handling code here:
        int index = tb_etudiant.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Selectionner un etudiant");
        } else {
            int id = (int) tb_etudiant.getValueAt(index, 0);
            EtudiantDao edao = new EtudiantDao();
            edao.supprimer(id);
            vider();
            listeEtudiant();
        }

    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void tb_etudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_etudiantMouseClicked
 
        // TODO add your handling code here:
        int index = tb_etudiant.getSelectedRow();
        if (index != -1) {
            int id = (int) tb_etudiant.getValueAt(index, 0);
            EtudiantDao edao = new EtudiantDao();
            Etudiant et = edao.recherche(id);
            txt_nom.setText(et.getNom());
            txt_prenom.setText(et.getPrenom());
            txt_classe.setText(et.getClasse());
            txt_telephone.setText(et.getTelephone());
        }
    }//GEN-LAST:event_tb_etudiantMouseClicked

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        // TODO add your handling code here:
        int index = tb_etudiant.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Selectionner un etudiant");
        } else {
            int id = (int) tb_etudiant.getValueAt(index, 0);
            String nom = txt_nom.getText();
            String prenom = txt_prenom.getText();
            String classe = txt_classe.getText();
            String telephone = txt_telephone.getText();
            Etudiant et = new Etudiant(nom, prenom, classe, telephone);
            EtudiantDao edao = new EtudiantDao();
            edao.modifier(et,id);
            vider();
            listeEtudiant();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed
//METHODE POUR VIDER LES CHAMPS

    private void vider() {
        txt_nom.setText("");
        txt_prenom.setText("");
        txt_classe.setText("");
        txt_telephone.setText("");
        DefaultTableModel model = (DefaultTableModel) tb_etudiant.getModel();
        model.setRowCount(0);
    }

    //AFFICHAGE DES ETUDIANTS DANS LE TABLEAU
    private void listeEtudiant() {
        EtudiantDao edao = new EtudiantDao();
        List<Etudiant> le = edao.liste();
        DefaultTableModel model = (DefaultTableModel) tb_etudiant.getModel();
        for (Etudiant et : le) {
            model.addRow(new Object[]{
                et.getIde(),
                et.getNom(),
                et.getPrenom(),
                et.getClasse(),
                et.getTelephone()
            });
        }
        tb_etudiant.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_etudiant;
    private javax.swing.JTextField txt_classe;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JFormattedTextField txt_telephone;
    // End of variables declaration//GEN-END:variables
}
